# Generated by Django 2.2.9 on 2020-02-12 09:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='inchurge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_projs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comm',
            name='created_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 2, 12, 1, 43, 28, 72277)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='created_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 2, 12, 1, 43, 28, 72277)),
        ),
    ]
